name: Repository Dispatch update build

defaults:
  run:
    shell: bash

on:
  repository_dispatch:
    types: [upx-frontend-build]
  workflow_dispatch:

jobs:
  update_build:
    runs-on: ubuntu-latest
    env:
      UPX_BUILD_NAME: ${{ github.event.client_payload.outputs.build_name }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Update upx-frontend build version
        run: |
          echo "Updating UPX build version to $UPX_BUILD_NAME"
          DEVENV_PATH=./components/upx-frontend/devenv
          sed -i -e s/UPX_FRONTEND_VERSION.*$/UPX_FRONTEND_VERSION=\"$TEST_VAR\"/g $DEVENV_PATH
          echo "$(<$DEVENV_PATH )"