name: 'Repo dispatch trigger'

on:
  push:
  workflow_dispatch:

jobs:

  deploy-to-gcs-bucket:
    runs-on: ubuntu-latest
    env:
       BUILD_NAME: ${{ github.sha }}
    steps:
      - name: Set build name
        run: |
          echo "Build name: $BUILD_NAME"
      - name: Dispatch build name to Aura repo
        uses: peter-evans/repository-dispatch@v3
        with:
#          token: ${{ secrets.AURA_REPOSITORY_DISPATCH_TOKEN }}
          repository: dan-jmc/gh-actions-playground
          event-type: upx-frontend-build
          client-payload: |-
            {
              "build_name": ${{ env.BUILD_NAME }}
            }